repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
  - repo: https://github.com/awslabs/git-secrets
    rev: 99d01d58ebcc06e237c0e3f3ff5ae628aeef6aa6
    hooks:
      - id: git-secrets
        verbose: true
        entry: "git-secrets --register-aws"
        language: script
        name: git-secrets-register-aws-provider
      - id: git-secrets
        verbose: true
        entry: "git-secrets --scan"
        language: script
        name: git-secrets-scan
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v0.75.1
    hooks:
      - id: cfn-lint
        entry: cfn-lint
        files: ^.*(Cfn|cfn)\.(yml|yaml)$
        language: python
        verbose: true
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.37.0"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.37.0
          - eslint-plugin-react
